
# Define all needed data for the sensebox
detection:
  saveFolder: notUsedYet
  threshold: 0.5
email:
  images: 3
  receiver:
    email: 
  sender:
    email: 
    password: 
  wanted: true
folderPath: /home/pi/countYourBirds
environmentPath: /home/pi/birds-env
sensebox:
  account:
    email: 
    password: 
  coordinates:
    latitude: 
    longitude: 
  id: notSet
  senseboxName: 
  sensors:
    all: 
  updateeveryhour: 1


